conditioning:
  method: ps
  params:
    scale: 1.0

data:
  name: ffhq
  root: ./data/DIV2K_HR_test_30/ #Êç¢data!!!
  image_size: 256

measurement:
  operator:
    name: phase_retrieval
    oversample: 2.0

  noise: 
    name: gaussian
    sigma: 0.05